### ISSUE TITLE
plugin loads fine but has no effect

### ISSUE THREAD

**Issue by kaarrot** [ltcmelo/uaiso-plugins#5]
Sorry this is a bit vague title but I'm not sure how to collect more information from the current qtCreator session.
- plugin seems to load fine and and the new uaiso entry shows up in the Options panel.
- uaiso plugin is enabled
- default qt_python plugin is unloaded
- path to the python libs are all set
  Still when editing a python file I don't get any completion feedback.

Is there anything else I can provide to determine the problem.
The only other case I didn't test, is to build for the very same QtCreator version you were using in the video. At the moment I'm on  newer one (3.6.82).
Would you be able to test with that specific version?

**Comment by ltcmelo** [comment]
First of all, make sure that you're opening the Python file with the Uaiso editor (to eliminate the case in which Qt Creator falls back to the default text editor). You can do so by following `Open File With...' and, once the file is selected, choosing the Uaiso option.

Now, do you get any completion? If not, do you get at least syntax highlighting?

On the video I used a quite old Qt Creator version. In fact, I haven't tested the plugin with newer versions. The current code was patched to 3.6 by a contributor. But one thing to keep in mind is that you should compile both Uaiso and Qt Creator with the same compiler/options. Otherwise, you might face a runtime error that might not be so obvious to decipher.

**Comment by ltcmelo** [comment]
I'll assume this can be closed. If not, please re-open.
